/*RELATÓRIO CODCLIENTE X ORDEM DE SERVIÇO*/
SELECT C.CODCLIENTE, OS.COD_ORDEMSERVICO, OS.DT_ABERTURA, OS.DT_PREV_ATENDIMENTO, OS.DT_EFET_ATENDIMENTO FROM ORDENSSERVICOS OS INNER JOIN CLIENTES C ON  OS.CODCLIENTE = C.CODCLIENTE  ORDER BY C.CODCLIENTE
