/*RELATÓRIO DE SERVICOS REALIZADOS*/
SELECT C.CODCLIENTE
, OS.COD_ORDEMSERVICO
, S.COD_SERVICO
, S.NOME
, S.CAT
, S.VLR_UNITARIO
, S.TEMPO_EXECUO
, S.GARANTIA
FROM SERVICOS S 
INNER JOIN ORDENSSERVICOS OS 
ON S.COD_ORDEMSERVICO = OS.COD_ORDEMSERVICO 
INNER JOIN CLIENTES C 
ON C.CODCLIENTE = S.CODCLIENTE
ORDER BY S.COD_SERVICO